from os import path
from os.path import join
from spectre7 import utils

Import("env")

env.Replace(
    CPPPATH = [".", env.ENGINE_SRC, join(env.ENGINE_SRC, "platform", env.PLATFORM_NAME), "include", "include/bullet"],
    CCFLAGS = ["-std=c++17", "-g", "-fpermissive", "-fdiagnostics-color=always", f"-DGIT_COMMIT_HASH='\"{env.getGitHash()}\"'", "-Linclude/lib/vita", "-Wl,-rpath include/lib/vita", "-lbox2d"],
    LINKFLAGS = ["-g"],
    LIBPATH = [env.LIB_DIR],
    LIBS = [
        "yaml-cpp",
        "box2d",
        "raylib",
        "bullet"
    ],
    CXX = "g++",
)

if path.isdir(env.DIRECTORY + "/include/lib/" + env.PLATFORM_NAME):
    env.Append(LIBPATH = "include/lib/" + env.PLATFORM_NAME)

previous_output = ""
def convertSconsLine(self, line: str, progress: int, out):
    global previous_output

    line = line.strip()
    progress = str(min(100, progress)) # Progress can exceed 100 in some cases
    for i in range(3 - len(progress)):
        progress = " " + progress
    progress = f"[{progress}%]"

    def compilingExternal(path: str, skip: bool):
        lib = path.split("/")[0]
        path = "/".join(path.split("/")[1:])

        ret = "Compiling " + utils.format_colour(env.COLOURS["skip" if skip else "compile"]["colour"], lib, env.COLOURS["skip" if skip else "compile"]["attrs"])
        
        if ret in previous_output:
            a = '\x1b[1A'
            b = '\x1b[2K'
            out.write(a + b)
            out.flush()

        if skip:
            ret += " (skipping)"
        else:
            ret += " | " + utils.format_colour(env.COLOURS["skip" if skip else "compile"]["colour"], path, env.COLOURS["skip" if skip else "compile"]["attrs"])
        return ret

    if line.endswith(" is up to date."):
        path = line.split("`")[1].split("'")[0].replace(".o", ".cpp").replace(env.OBJ_DIR + "project/", env.PROJECT_SRC)#.replace(env.OBJ_DIR + "engine/", env.ENGINE_SRC)
        if path.startswith(join(env.OBJ_DIR, env.ENGINE_EXTERNAL)):
            line = compilingExternal(path.removeprefix(join(env.OBJ_DIR, env.ENGINE_EXTERNAL)), True)
        else:
            line = "Compiling " + utils.format_colour(env.COLOURS["skip"]["colour"], path, env.COLOURS["skip"]["attrs"]) + " (skipping)"
    elif line.startswith("Compiling "):
        path = line[len("Compiling "):]
        if path.startswith(env.ENGINE_EXTERNAL):
            line = compilingExternal(path.removeprefix(env.ENGINE_EXTERNAL), False)
        else:
            line = "Compiling " + utils.format_colour(env.COLOURS["compile"]["colour"], path, env.COLOURS["compile"]["attrs"])
    elif line.startswith("ranlib "):
        line = "Indexing library " + utils.format_colour(env.COLOURS["index"]["colour"], line[len("ranlib "):], env.COLOURS["index"]["attrs"])
    elif line.startswith("Linking "):
        line = "Linking program " + utils.format_colour(env.COLOURS["link"]["colour"], line[len("Linking "):], env.COLOURS["link"]["attrs"])
    elif line == "scons: Building targets ...":
        return utils.format_colour("magenta", f"\n - - Starting build ({env.PLATFORM_NAME}) - - \n", ["reverse"])

    previous_output = f"{utils.format_colour(env.COLOURS['progress']['colour'], progress, env.COLOURS['progress']['attrs'])} {line}"
    return previous_output

env.AddMethod(convertSconsLine)

if not GetOption("verbose"):
    env["CXXCOMSTR"]  = "Compiling $SOURCE"
    env["LINKCOMSTR"] = "Linking $TARGET"

SConscript(env.PLATFORM_LIST[env.PLATFORM_NAME])