import os

Import("env")

def runProjectBinary(file):
    if not env.RUN_AFTER_BUILD:
        return

    path = str(file)

    if not GetOption("run_tests"):
        os.system(path)
    else:
        os.system(env.BUILD_DIR + env.TEST_BINARY_NAME + " && " + path)

if GetOption("target") == "debug":
    env.Append(LIBS = ["bfd", "boost_unit_test_framework"])

env.Append(CCFLAGS = "-rdynamic")

env.runProjectBinary = runProjectBinary